### PR TITLE
Update default_recovery_ui.c

### PR DESCRIPTION
**Pull request by shengtan**
translate default_recovery_ui into Simplified Chinese

### CODE REVIEW

**Comment by rtfpessoa** [comment]
I cannot accept this patch, english is the default language. I Cannot understand chinese :(

**Comment by github-wang** [comment]
i love English

**Comment by github-wang** [comment]
Translated into Chinese is also possible

**Comment by github-wang** [comment]
@rtfpessoa   https://github.com/xiaolu?tab=repositories
He has cwm in the cultural code, can learn from under it?

**Pull request closed without merging**
